# Generated by Django 3.2.7 on 2021-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visualization',
            name='imgPreview',
            field=models.ImageField(null=True, upload_to='images/visualizationPreview'),
        ),
    ]
