# Generated by Django 3.2.7 on 2021-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211111_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='imgPreview',
            field=models.ImageField(blank=True, null=True, upload_to='images/visualizationPreview'),
        ),
    ]
