# Generated by Django 3.2.7 on 2021-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_visualization_imgpreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='imgPreview',
            field=models.ImageField(blank=True, null=True, upload_to='images/visualizationPreviews'),
        ),
    ]
