# Generated by Django 3.2.7 on 2021-11-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_visualization_imgpreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='public',
        ),
    ]
