# Generated by Django 3.2.7 on 2021-11-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_visualization_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='imgPreview',
        ),
    ]
